### ISSUE TITLE
Include Geekcreit 2 Channel AC 85V-250V

### ISSUE THREAD

**Issue by jgyoldi** [peterbuga/HASS-sonoff-ewelink#13]
Hello,

The module Geekcreit 2 Channel AC 85V-250V can be linked to ewlink. It appears as a switch at Home assistant (instead of two) and it doesn´t work. Here they are the parameters that appear in devices.json:

[devices.txt](https://github.com/peterbuga/HASS-sonoff-ewelink/files/2657570/devices.txt)

Regards,

**Comment by 2016for** [comment]
Just went through the file, don't see a reason for it to not work.

Could you please add the custom components to your configuation.yaml under your logger: component

```
logger:
  default: warning
  logs:
    custom_components.sonoff: debug
    custom_components.switch.sonoff: debug

```
And then restart HA and go to dev-info, press the refresh icon (not the word refresh) at the bottom right of the page and then share the relevant debug/warning/error messages.
