### ISSUE TITLE
Check config stuck on loop

### ISSUE THREAD

**Issue by Poker1410** [peterbuga/HASS-sonoff-ewelink#265]
Hi all
I have Hass.io (64bit) installed on a RaspberryPi 4 8GB (32bit is not available on 8GB). 
I am trying to install the sonoff component but I am having problems with the configuration.yaml file.

As soon as I add to the config.yaml the sonoff lines, as per below, hassio's check config sits there and "thinks" with the spinning circle.
If I comment the sonoff component in the config.yaml the check config gives me green light immediately.
This makes me say that it is an issue with the sonoff config...?
The .py files are saved, as per instructions, in custom_components/sonoff.

Restarting the raspberrypi is not an option because otherwise Hassio does not start anymore (I guess it is because it is trying to check config.yaml and gets "stuck"). hassio does not give any errors in the log.

Any help would be greatly appreciated!

```

sonoff:
  username: email@abcd.com
  password: password
  scan_interval: 60 
  grace_period: 600 
  api_region: 'cn' 
```
