### ISSUE TITLE
Sonoffs turn from off to off occasionally.

### ISSUE THREAD

**Issue by krasatos** [peterbuga/HASS-sonoff-ewelink#93]
Not an issue, more like an observation but thought i should mention it in case it is usefull or it means something more to you guys.

I have my sonoffs running my irrigation system so while testing (in order to be sure) i set up an automation that notifies me on any state change of my ewelink-connected sonoffs.
````
- id: 'XXXXXXX'
  alias: Notify Failsafe Irrigation 
  trigger:
  - entity_id: switch.XXXXXXX, switch.XXXXXXX, switch.XXXXXXX, switch.XXXXXXX, switch.XXXXXXX
    platform: state
  condition: []
  action:
  - data_template:
      message: "Switch {{ trigger.entity_id }} changed from {{ trigger.from_state.state}} to {{ trigger.to_state.state }} at {{ now().strftime('%H:%M')}}"
      title: Irrigation Alert
    service: notify.notify_html5

````

Throughout the day, (3-4 times daily i think) i get a set of notifications (one for every switch) that "switch XXX changed from off to off at xx:xx".

This does not affect me at all, i would guess it's a reconnection issue or a failsafe?
I just thought i should mention it, in case you guys missed it.
(feel free to close/delete my issue if this is not at all important)

Thanks again for this solution :)
