### ISSUE TITLE
Not working when used as a package

### ISSUE THREAD

**Issue by GuyKh** [peterbuga/HASS-sonoff-ewelink#95]
In configuration.yaml - I have this:
`packages: !include_dir_named packages`

Then I created a file: ..\packages\sonoff.yaml
```
sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  api_region: 'eu'
```

And I'm getting this error when running:
```
Failed config
  homeassistant.packages.sonoff.sonoff: 
    - Package sonoff setup failed. Component sonoff does not exist
    - sonoff: [source /home/travis/build/XXXXXXX...../packages/sonoff.yaml:1]
        api_region: eu
        password: pass
        username: username
```

Is there a way to make this work?
